services:
  db:
    extends:
      file: docker/compose/base.compose.yaml
      service: base_db
    container_name: db
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: db

  hop:
    extends:
      file: docker/compose/base.compose.yaml
      service: base_hop
    container_name: hop
    ports:
      - "8080:8080"
    volumes:
      - xml:/files/jade-extrator/datasets/lattes_xml
    depends_on:
      db:
        condition: service_healthy

  api:
    extends:
      file: docker/compose/base.compose.yaml
      service: base_api
    container_name: api
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql+asyncpg://postgres:postgres@db:5432/db
      ADMIN_DATABASE_URL: postgresql+asyncpg://postgres:postgres@db:5432/db_admin
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - xml:/app/storage/xml
    env_file:
      - .env

volumes:
  db:
  xml: