services:
  db:
    image: pgvector/pgvector:pg17
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ${COMPOSE_PROJECT_NAME}
    ports:
      - "127.0.0.1:${DB_PORT}:5432"
    volumes:
      - db:/var/lib/postgresql/data
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  api:
    build: .
    image: ${COMPOSE_PROJECT_NAME}
    entrypoint: ./entrypoint.sh
    ports:
      - "127.0.0.1:${API_PORT}:8000"
    environment:
      ALTERNATIVE_CNPQ_SERVICE: ${ALTERNATIVE_CNPQ_SERVICE}
      DATABASE_URL: postgresql+asyncpg://postgres:postgres@db:5432/${COMPOSE_PROJECT_NAME}
      ADMIN_DATABASE_URL: postgresql+asyncpg://postgres:postgres@db:5432/${COMPOSE_PROJECT_NAME}_admin
    volumes:
      - xml:/app/storage/xml
      - logs:/app/logs
    restart: always
    depends_on:
      db:
        condition: service_healthy

volumes:
  db:
  xml:
  logs: