version: 1
disable_existing_loggers: False

formatters:
  standard:
    format: "%(asctime)s - %(levelname)s - %(message)s"

handlers:
  console:
    class: logging.StreamHandler
    level: INFO
    formatter: standard
    stream: ext://sys.stdout

  file:
    class: logging.FileHandler
    level: INFO
    formatter: standard
    filename: simcc.log

  error_file:
    class: logging.FileHandler
    level: ERROR
    formatter: standard
    filename: simcc.error.log

loggers:
  uvicorn:
    level: INFO
    handlers: [console, file, error_file]
    propagate: no

  uvicorn.error:
    level: ERROR
    handlers: [console, error_file]
    propagate: no

  uvicorn.access:
    level: INFO
    handlers: [console, file]
    propagate: no
