"""add_quadrennial_to_article

Revision ID: 0678ea61ca27
Revises: 0990b6488f64
Create Date: 2026-07-30 15:32:46.035784

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0678ea61ca27'
down_revision: Union[str, Sequence[str], None] = '0990b6488f64'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bibliographic_production_article', sa.Column('quadrennial', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bibliographic_production_article', 'quadrennial')
    # ### end Alembic commands ###
