"""empty message

Revision ID: 0990b6488f64
Revises: 5077a1e26b1d
Create Date: 2026-07-03 18:59:08.220219

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0990b6488f64'
down_revision: Union[str, Sequence[str], None] = '5077a1e26b1d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'city', ['name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'city', type_='unique')
    # ### end Alembic commands ###
