"""empty message

Revision ID: 0b48abec391b
Revises: 5d86e7e7fae8
Create Date: 2026-05-24 19:34:12.373655

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0b48abec391b'
down_revision: Union[str, Sequence[str], None] = '5d86e7e7fae8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('researcher_production', sa.Column('area_specialty', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('researcher_production', 'area_specialty')
    # ### end Alembic commands ###
