"""empty message

Revision ID: 137dfa8f8771
Revises: a8f1e23a1104
Create Date: 2026-05-24 18:53:04.335565

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '137dfa8f8771'
down_revision: Union[str, Sequence[str], None] = 'a8f1e23a1104'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('researcher', sa.Column('docente', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('researcher', 'docente')
    # ### end Alembic commands ###
