"""empty message

Revision ID: 5077a1e26b1d
Revises: d0ceb77678ac
Create Date: 2026-06-08 13:04:27.562944

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5077a1e26b1d'
down_revision: Union[str, Sequence[str], None] = 'd0ceb77678ac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'uid',
               existing_type=sa.VARCHAR(),
               nullable=True,
               schema='admin')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'uid',
               existing_type=sa.VARCHAR(),
               nullable=False,
               schema='admin')
    # ### end Alembic commands ###
