"""empty message

Revision ID: 5b9d6478ca92
Revises: ddff76fe9416
Create Date: 2026-05-26 13:04:44.904953

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5b9d6478ca92'
down_revision: Union[str, Sequence[str], None] = 'ddff76fe9416'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('openalex_article', sa.Column('created_at', sa.DateTime(timezone=True), nullable=False))
    op.add_column('openalex_article', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False))
    op.alter_column('openalex_article', 'article_institution',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('openalex_article', 'authors_institution',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('openalex_article', 'authors',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('openalex_article', 'pdf',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('openalex_article', 'landing_page_url',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('openalex_article', 'keywords',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)
    op.create_index('idx_openalex_article_issn', 'openalex_article', ['issn'], unique=False)
    op.create_index('idx_openalex_article_language', 'openalex_article', ['language'], unique=False)
    op.create_unique_constraint('uq_openalex_article_article_id', 'openalex_article', ['article_id'])
    op.create_unique_constraint(None, 'openalex_article', ['article_id'])
    op.drop_constraint(op.f('openalex_article_article_id_fkey'), 'openalex_article', type_='foreignkey')
    op.create_foreign_key(None, 'openalex_article', 'bibliographic_production', ['article_id'], ['id'], ondelete='CASCADE')
    op.add_column('openalex_researcher', sa.Column('created_at', sa.DateTime(timezone=True), nullable=False))
    op.add_column('openalex_researcher', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False))
    op.alter_column('openalex_researcher', 'orcid',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=19),
               existing_nullable=True)
    op.create_index('idx_openalex_researcher_openalex', 'openalex_researcher', ['openalex'], unique=False)
    op.create_index('idx_openalex_researcher_orcid', 'openalex_researcher', ['orcid'], unique=False)
    op.create_unique_constraint('uq_openalex_researcher_orcid', 'openalex_researcher', ['orcid'])
    op.create_unique_constraint('uq_openalex_researcher_researcher_id', 'openalex_researcher', ['researcher_id'])
    op.drop_constraint(op.f('openalex_researcher_researcher_id_fkey'), 'openalex_researcher', type_='foreignkey')
    op.create_foreign_key(None, 'openalex_researcher', 'researcher', ['researcher_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'openalex_researcher', type_='foreignkey')
    op.create_foreign_key(op.f('openalex_researcher_researcher_id_fkey'), 'openalex_researcher', 'researcher', ['researcher_id'], ['id'])
    op.drop_constraint('uq_openalex_researcher_researcher_id', 'openalex_researcher', type_='unique')
    op.drop_constraint('uq_openalex_researcher_orcid', 'openalex_researcher', type_='unique')
    op.drop_index('idx_openalex_researcher_orcid', table_name='openalex_researcher')
    op.drop_index('idx_openalex_researcher_openalex', table_name='openalex_researcher')
    op.alter_column('openalex_researcher', 'orcid',
               existing_type=sa.String(length=19),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    op.drop_column('openalex_researcher', 'updated_at')
    op.drop_column('openalex_researcher', 'created_at')
    op.drop_constraint(None, 'openalex_article', type_='foreignkey')
    op.create_foreign_key(op.f('openalex_article_article_id_fkey'), 'openalex_article', 'bibliographic_production', ['article_id'], ['id'])
    op.drop_constraint(None, 'openalex_article', type_='unique')
    op.drop_constraint('uq_openalex_article_article_id', 'openalex_article', type_='unique')
    op.drop_index('idx_openalex_article_language', table_name='openalex_article')
    op.drop_index('idx_openalex_article_issn', table_name='openalex_article')
    op.alter_column('openalex_article', 'keywords',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.alter_column('openalex_article', 'landing_page_url',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.alter_column('openalex_article', 'pdf',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.alter_column('openalex_article', 'authors',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.alter_column('openalex_article', 'authors_institution',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.alter_column('openalex_article', 'article_institution',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.drop_column('openalex_article', 'updated_at')
    op.drop_column('openalex_article', 'created_at')
    # ### end Alembic commands ###
