"""empty message

Revision ID: 6b6a0bb12051
Revises: 0b48abec391b
Create Date: 2026-05-24 19:36:31.850712

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6b6a0bb12051'
down_revision: Union[str, Sequence[str], None] = '0b48abec391b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('researcher_production', sa.Column('organ', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('researcher_production', 'organ')
    # ### end Alembic commands ###
