"""empty message

Revision ID: 6cc7cda43d27
Revises: 137dfa8f8771
Create Date: 2026-05-24 19:21:14.356095

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6cc7cda43d27'
down_revision: Union[str, Sequence[str], None] = '137dfa8f8771'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('researcher_production', sa.Column('work_in_event', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('researcher_production', 'work_in_event')
    # ### end Alembic commands ###
