"""empty message

Revision ID: 8784cc13525f
Revises: 97f602cb7b01
Create Date: 2026-06-07 08:43:56.712829

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8784cc13525f'
down_revision: Union[str, Sequence[str], None] = '97f602cb7b01'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('routine', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False), schema='logs')
    op.create_unique_constraint('uk_routine_type', 'routine', ['type'], schema='logs')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uk_routine_type', 'routine', schema='logs', type_='unique')
    op.drop_column('routine', 'created_at', schema='logs')
    # ### end Alembic commands ###
