"""empty message

Revision ID: 906555ad3551
Revises: 8784cc13525f
Create Date: 2026-06-08 13:01:44.991218

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '906555ad3551'
down_revision: Union[str, Sequence[str], None] = '8784cc13525f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('orcid_id', sa.String(), nullable=True), schema='admin')
    op.add_column('users', sa.Column('username', sa.String(), nullable=True), schema='admin')
    op.add_column('users', sa.Column('icon_url', sa.Text(), nullable=True), schema='admin')
    op.add_column('users', sa.Column('cover_url', sa.Text(), nullable=True), schema='admin')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'cover_url', schema='admin')
    op.drop_column('users', 'icon_url', schema='admin')
    op.drop_column('users', 'username', schema='admin')
    op.drop_column('users', 'orcid_id', schema='admin')
    # ### end Alembic commands ###
