"""empty message

Revision ID: af7a03c3482f
Revises: 6b6a0bb12051
Create Date: 2026-05-26 10:51:23.949713

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'af7a03c3482f'
down_revision: Union[str, Sequence[str], None] = '6b6a0bb12051'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('graduate_program_researcher', sa.Column('tag', sa.String(), nullable=True))
    op.drop_constraint(op.f('graduate_program_researcher_graduate_program_id_fkey'), 'graduate_program_researcher', type_='foreignkey')
    op.drop_constraint(op.f('graduate_program_researcher_researcher_id_fkey'), 'graduate_program_researcher', type_='foreignkey')
    op.create_foreign_key(None, 'graduate_program_researcher', 'researcher', ['researcher_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.create_foreign_key(None, 'graduate_program_researcher', 'graduate_program', ['graduate_program_id'], ['graduate_program_id'], onupdate='CASCADE', ondelete='CASCADE')
    op.add_column('researcher', sa.Column('extra_field', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('researcher', 'extra_field')
    op.drop_constraint(None, 'graduate_program_researcher', type_='foreignkey')
    op.drop_constraint(None, 'graduate_program_researcher', type_='foreignkey')
    op.create_foreign_key(op.f('graduate_program_researcher_researcher_id_fkey'), 'graduate_program_researcher', 'researcher', ['researcher_id'], ['id'])
    op.create_foreign_key(op.f('graduate_program_researcher_graduate_program_id_fkey'), 'graduate_program_researcher', 'graduate_program', ['graduate_program_id'], ['graduate_program_id'])
    op.drop_column('graduate_program_researcher', 'tag')
    # ### end Alembic commands ###
