"""empty message

Revision ID: b8a8878e688a
Revises: 0678ea61ca27
Create Date: 2026-08-14 00:20:27.568866

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b8a8878e688a'
down_revision: Union[str, Sequence[str], None] = '0678ea61ca27'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('advisory_activity_researcher_id_fkey'), 'advisory_activity', type_='foreignkey')
    op.create_foreign_key(None, 'advisory_activity', 'researcher', ['researcher_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('artistic_production_researcher_id_fkey'), 'artistic_production', type_='foreignkey')
    op.create_foreign_key(None, 'artistic_production', 'researcher', ['researcher_id'], ['id'], ondelete='CASCADE')
    op.alter_column('bibliographic_production', 'researcher_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_constraint(op.f('bibliographic_production_researcher_id_fkey'), 'bibliographic_production', type_='foreignkey')
    op.create_foreign_key(None, 'bibliographic_production', 'researcher', ['researcher_id'], ['id'], ondelete='CASCADE')
    op.alter_column('brand', 'researcher_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_constraint(op.f('brand_researcher_id_fkey'), 'brand', type_='foreignkey')
    op.create_foreign_key(None, 'brand', 'researcher', ['researcher_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('didactic_material_researcher_id_fkey'), 'didactic_material', type_='foreignkey')
    op.create_foreign_key(None, 'didactic_material', 'researcher', ['researcher_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('education_researcher_id_fkey'), 'education', type_='foreignkey')
    op.create_foreign_key(None, 'education', 'researcher', ['researcher_id'], ['id'], ondelete='CASCADE')
    op.alter_column('event_organization', 'researcher_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_constraint(op.f('event_organization_researcher_id_fkey'), 'event_organization', type_='foreignkey')
    op.create_foreign_key(None, 'event_organization', 'researcher', ['researcher_id'], ['id'], ondelete='CASCADE')
    op.alter_column('foment', 'researcher_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_constraint(op.f('foment_researcher_id_fkey'), 'foment', type_='foreignkey')
    op.create_foreign_key(None, 'foment', 'researcher', ['researcher_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('graduate_program_student_researcher_id_fkey'), 'graduate_program_student', type_='foreignkey')
    op.create_foreign_key(None, 'graduate_program_student', 'researcher', ['researcher_id'], ['id'], ondelete='CASCADE')
    op.alter_column('guidance', 'researcher_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_constraint(op.f('guidance_researcher_id_fkey'), 'guidance', type_='foreignkey')
    op.create_foreign_key(None, 'guidance', 'researcher', ['researcher_id'], ['id'], ondelete='CASCADE')
    op.alter_column('industrial_design', 'researcher_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_constraint(op.f('industrial_design_researcher_id_fkey'), 'industrial_design', type_='foreignkey')
    op.create_foreign_key(None, 'industrial_design', 'researcher', ['researcher_id'], ['id'], ondelete='CASCADE')
    op.alter_column('labs', 'researcher_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_constraint(op.f('labs_researcher_id_fkey'), 'labs', type_='foreignkey')
    op.create_foreign_key(None, 'labs', 'researcher', ['researcher_id'], ['id'], ondelete='CASCADE')
    op.alter_column('letter_map_or_similar', 'researcher_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_constraint(op.f('letter_map_or_similar_researcher_id_fkey'), 'letter_map_or_similar', type_='foreignkey')
    op.create_foreign_key(None, 'letter_map_or_similar', 'researcher', ['researcher_id'], ['id'], ondelete='CASCADE')
    op.alter_column('maintenance_artistic_work', 'researcher_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_constraint(op.f('maintenance_artistic_work_researcher_id_fkey'), 'maintenance_artistic_work', type_='foreignkey')
    op.create_foreign_key(None, 'maintenance_artistic_work', 'researcher', ['researcher_id'], ['id'], ondelete='CASCADE')
    op.alter_column('mockup', 'researcher_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_constraint(op.f('mockup_researcher_id_fkey'), 'mockup', type_='foreignkey')
    op.create_foreign_key(None, 'mockup', 'researcher', ['researcher_id'], ['id'], ondelete='CASCADE')
    op.alter_column('other_technical_production', 'researcher_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_constraint(op.f('other_technical_production_researcher_id_fkey'), 'other_technical_production', type_='foreignkey')
    op.create_foreign_key(None, 'other_technical_production', 'researcher', ['researcher_id'], ['id'], ondelete='CASCADE')
    op.alter_column('participation_events', 'researcher_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_constraint(op.f('participation_events_researcher_id_fkey'), 'participation_events', type_='foreignkey')
    op.create_foreign_key(None, 'participation_events', 'researcher', ['researcher_id'], ['id'], ondelete='CASCADE')
    op.alter_column('patent', 'researcher_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_constraint(op.f('patent_researcher_id_fkey'), 'patent', type_='foreignkey')
    op.create_foreign_key(None, 'patent', 'researcher', ['researcher_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('process_or_technique_researcher_id_fkey'), 'process_or_technique', type_='foreignkey')
    op.create_foreign_key(None, 'process_or_technique', 'researcher', ['researcher_id'], ['id'], ondelete='CASCADE')
    op.alter_column('publishing', 'researcher_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_constraint(op.f('publishing_researcher_id_fkey'), 'publishing', type_='foreignkey')
    op.create_foreign_key(None, 'publishing', 'researcher', ['researcher_id'], ['id'], ondelete='CASCADE')
    op.alter_column('radio_or_tv_program', 'researcher_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_constraint(op.f('radio_or_tv_program_researcher_id_fkey'), 'radio_or_tv_program', type_='foreignkey')
    op.create_foreign_key(None, 'radio_or_tv_program', 'researcher', ['researcher_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('registered_cultivar_researcher_id_fkey'), 'registered_cultivar', type_='foreignkey')
    op.create_foreign_key(None, 'registered_cultivar', 'researcher', ['researcher_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('relevant_production_researcher_id_fkey'), 'relevant_production', type_='foreignkey')
    op.create_foreign_key(None, 'relevant_production', 'researcher', ['researcher_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('research_group_researcher_researcher_id_fkey'), 'research_group_researcher', type_='foreignkey')
    op.create_foreign_key(None, 'research_group_researcher', 'researcher', ['researcher_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('research_project_researcher_id_fkey'), 'research_project', type_='foreignkey')
    op.create_foreign_key(None, 'research_project', 'researcher', ['researcher_id'], ['id'], ondelete='CASCADE')
    op.alter_column('research_report', 'researcher_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_constraint(op.f('research_report_researcher_id_fkey'), 'research_report', type_='foreignkey')
    op.create_foreign_key(None, 'research_report', 'researcher', ['researcher_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('researcher_address_researcher_id_fkey'), 'researcher_address', type_='foreignkey')
    op.create_foreign_key(None, 'researcher_address', 'researcher', ['researcher_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('researcher_area_expertise_researcher_id_fkey'), 'researcher_area_expertise', type_='foreignkey')
    op.create_foreign_key(None, 'researcher_area_expertise', 'researcher', ['researcher_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('researcher_ind_prod_researcher_id_fkey'), 'researcher_ind_prod', type_='foreignkey')
    op.create_foreign_key(None, 'researcher_ind_prod', 'researcher', ['researcher_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('researcher_production_researcher_id_fkey'), 'researcher_production', type_='foreignkey')
    op.create_foreign_key(None, 'researcher_production', 'researcher', ['researcher_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('researcher_professional_experience_researcher_id_fkey'), 'researcher_professional_experience', type_='foreignkey')
    op.create_foreign_key(None, 'researcher_professional_experience', 'researcher', ['researcher_id'], ['id'], ondelete='CASCADE')
    op.alter_column('short_course', 'researcher_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_constraint(op.f('short_course_researcher_id_fkey'), 'short_course', type_='foreignkey')
    op.create_foreign_key(None, 'short_course', 'researcher', ['researcher_id'], ['id'], ondelete='CASCADE')
    op.alter_column('short_course_taught', 'researcher_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_constraint(op.f('short_course_taught_researcher_id_fkey'), 'short_course_taught', type_='foreignkey')
    op.create_foreign_key(None, 'short_course_taught', 'researcher', ['researcher_id'], ['id'], ondelete='CASCADE')
    op.alter_column('social_media_website_blog', 'researcher_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_constraint(op.f('social_media_website_blog_researcher_id_fkey'), 'social_media_website_blog', type_='foreignkey')
    op.create_foreign_key(None, 'social_media_website_blog', 'researcher', ['researcher_id'], ['id'], ondelete='CASCADE')
    op.alter_column('software', 'researcher_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_constraint(op.f('software_researcher_id_fkey'), 'software', type_='foreignkey')
    op.create_foreign_key(None, 'software', 'researcher', ['researcher_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('technical_work_researcher_id_fkey'), 'technical_work', type_='foreignkey')
    op.create_foreign_key(None, 'technical_work', 'researcher', ['researcher_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('technical_work_presentation_researcher_id_fkey'), 'technical_work_presentation', type_='foreignkey')
    op.create_foreign_key(None, 'technical_work_presentation', 'researcher', ['researcher_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('technical_work_program_researcher_id_fkey'), 'technical_work_program', type_='foreignkey')
    op.create_foreign_key(None, 'technical_work_program', 'researcher', ['researcher_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('technological_product_researcher_id_fkey'), 'technological_product', type_='foreignkey')
    op.create_foreign_key(None, 'technological_product', 'researcher', ['researcher_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('graduate_program_researcher_researcher_id_fkey'), 'graduate_program_researcher', schema='admin', type_='foreignkey')
    op.create_foreign_key(None, 'graduate_program_researcher', 'researcher', ['researcher_id'], ['researcher_id'], source_schema='admin', referent_schema='admin', ondelete='CASCADE')
    op.drop_constraint(op.f('graduate_program_student_researcher_id_fkey'), 'graduate_program_student', schema='admin', type_='foreignkey')
    op.create_foreign_key(None, 'graduate_program_student', 'researcher', ['researcher_id'], ['researcher_id'], source_schema='admin', referent_schema='admin', ondelete='CASCADE')
    op.drop_constraint(op.f('researcher_institution_researcher_id_fkey'), 'researcher_institution', schema='admin', type_='foreignkey')
    op.create_foreign_key(None, 'researcher_institution', 'researcher', ['researcher_id'], ['researcher_id'], source_schema='admin', referent_schema='admin', ondelete='CASCADE')
    op.drop_constraint(op.f('department_researcher_researcher_id_fkey'), 'department_researcher', schema='admin_ufmg', type_='foreignkey')
    op.create_foreign_key(None, 'department_researcher', 'researcher', ['researcher_id'], ['researcher_id'], source_schema='admin_ufmg', referent_schema='admin', ondelete='CASCADE')
    op.drop_constraint(op.f('researcher_researcher_id_fkey'), 'researcher', schema='admin_ufmg', type_='foreignkey')
    op.create_foreign_key(None, 'researcher', 'researcher', ['researcher_id'], ['researcher_id'], source_schema='admin_ufmg', referent_schema='admin', ondelete='CASCADE')
    op.create_foreign_key(None, 'departament_researcher', 'researcher', ['researcher_id'], ['researcher_id'], source_schema='ufmg', referent_schema='ufmg', ondelete='CASCADE')
    op.create_foreign_key(None, 'departament_researcher', 'departament', ['dep_id'], ['dep_id'], source_schema='ufmg', referent_schema='ufmg', ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'departament_researcher', schema='ufmg', type_='foreignkey')
    op.drop_constraint(None, 'departament_researcher', schema='ufmg', type_='foreignkey')
    op.drop_constraint(None, 'researcher', schema='admin_ufmg', type_='foreignkey')
    op.create_foreign_key(op.f('researcher_researcher_id_fkey'), 'researcher', 'researcher', ['researcher_id'], ['researcher_id'], source_schema='admin_ufmg', referent_schema='admin')
    op.drop_constraint(None, 'department_researcher', schema='admin_ufmg', type_='foreignkey')
    op.create_foreign_key(op.f('department_researcher_researcher_id_fkey'), 'department_researcher', 'researcher', ['researcher_id'], ['researcher_id'], source_schema='admin_ufmg', referent_schema='admin')
    op.drop_constraint(None, 'researcher_institution', schema='admin', type_='foreignkey')
    op.create_foreign_key(op.f('researcher_institution_researcher_id_fkey'), 'researcher_institution', 'researcher', ['researcher_id'], ['researcher_id'], source_schema='admin', referent_schema='admin')
    op.drop_constraint(None, 'graduate_program_student', schema='admin', type_='foreignkey')
    op.create_foreign_key(op.f('graduate_program_student_researcher_id_fkey'), 'graduate_program_student', 'researcher', ['researcher_id'], ['researcher_id'], source_schema='admin', referent_schema='admin')
    op.drop_constraint(None, 'graduate_program_researcher', schema='admin', type_='foreignkey')
    op.create_foreign_key(op.f('graduate_program_researcher_researcher_id_fkey'), 'graduate_program_researcher', 'researcher', ['researcher_id'], ['researcher_id'], source_schema='admin', referent_schema='admin')
    op.drop_constraint(None, 'technological_product', type_='foreignkey')
    op.create_foreign_key(op.f('technological_product_researcher_id_fkey'), 'technological_product', 'researcher', ['researcher_id'], ['id'])
    op.drop_constraint(None, 'technical_work_program', type_='foreignkey')
    op.create_foreign_key(op.f('technical_work_program_researcher_id_fkey'), 'technical_work_program', 'researcher', ['researcher_id'], ['id'])
    op.drop_constraint(None, 'technical_work_presentation', type_='foreignkey')
    op.create_foreign_key(op.f('technical_work_presentation_researcher_id_fkey'), 'technical_work_presentation', 'researcher', ['researcher_id'], ['id'])
    op.drop_constraint(None, 'technical_work', type_='foreignkey')
    op.create_foreign_key(op.f('technical_work_researcher_id_fkey'), 'technical_work', 'researcher', ['researcher_id'], ['id'])
    op.drop_constraint(None, 'software', type_='foreignkey')
    op.create_foreign_key(op.f('software_researcher_id_fkey'), 'software', 'researcher', ['researcher_id'], ['id'])
    op.alter_column('software', 'researcher_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_constraint(None, 'social_media_website_blog', type_='foreignkey')
    op.create_foreign_key(op.f('social_media_website_blog_researcher_id_fkey'), 'social_media_website_blog', 'researcher', ['researcher_id'], ['id'])
    op.alter_column('social_media_website_blog', 'researcher_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_constraint(None, 'short_course_taught', type_='foreignkey')
    op.create_foreign_key(op.f('short_course_taught_researcher_id_fkey'), 'short_course_taught', 'researcher', ['researcher_id'], ['id'])
    op.alter_column('short_course_taught', 'researcher_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_constraint(None, 'short_course', type_='foreignkey')
    op.create_foreign_key(op.f('short_course_researcher_id_fkey'), 'short_course', 'researcher', ['researcher_id'], ['id'])
    op.alter_column('short_course', 'researcher_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_constraint(None, 'researcher_professional_experience', type_='foreignkey')
    op.create_foreign_key(op.f('researcher_professional_experience_researcher_id_fkey'), 'researcher_professional_experience', 'researcher', ['researcher_id'], ['id'])
    op.drop_constraint(None, 'researcher_production', type_='foreignkey')
    op.create_foreign_key(op.f('researcher_production_researcher_id_fkey'), 'researcher_production', 'researcher', ['researcher_id'], ['id'])
    op.drop_constraint(None, 'researcher_ind_prod', type_='foreignkey')
    op.create_foreign_key(op.f('researcher_ind_prod_researcher_id_fkey'), 'researcher_ind_prod', 'researcher', ['researcher_id'], ['id'])
    op.drop_constraint(None, 'researcher_area_expertise', type_='foreignkey')
    op.create_foreign_key(op.f('researcher_area_expertise_researcher_id_fkey'), 'researcher_area_expertise', 'researcher', ['researcher_id'], ['id'])
    op.drop_constraint(None, 'researcher_address', type_='foreignkey')
    op.create_foreign_key(op.f('researcher_address_researcher_id_fkey'), 'researcher_address', 'researcher', ['researcher_id'], ['id'])
    op.drop_constraint(None, 'research_report', type_='foreignkey')
    op.create_foreign_key(op.f('research_report_researcher_id_fkey'), 'research_report', 'researcher', ['researcher_id'], ['id'])
    op.alter_column('research_report', 'researcher_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_constraint(None, 'research_project', type_='foreignkey')
    op.create_foreign_key(op.f('research_project_researcher_id_fkey'), 'research_project', 'researcher', ['researcher_id'], ['id'])
    op.drop_constraint(None, 'research_group_researcher', type_='foreignkey')
    op.create_foreign_key(op.f('research_group_researcher_researcher_id_fkey'), 'research_group_researcher', 'researcher', ['researcher_id'], ['id'])
    op.drop_constraint(None, 'relevant_production', type_='foreignkey')
    op.create_foreign_key(op.f('relevant_production_researcher_id_fkey'), 'relevant_production', 'researcher', ['researcher_id'], ['id'])
    op.drop_constraint(None, 'registered_cultivar', type_='foreignkey')
    op.create_foreign_key(op.f('registered_cultivar_researcher_id_fkey'), 'registered_cultivar', 'researcher', ['researcher_id'], ['id'])
    op.drop_constraint(None, 'radio_or_tv_program', type_='foreignkey')
    op.create_foreign_key(op.f('radio_or_tv_program_researcher_id_fkey'), 'radio_or_tv_program', 'researcher', ['researcher_id'], ['id'])
    op.alter_column('radio_or_tv_program', 'researcher_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_constraint(None, 'publishing', type_='foreignkey')
    op.create_foreign_key(op.f('publishing_researcher_id_fkey'), 'publishing', 'researcher', ['researcher_id'], ['id'])
    op.alter_column('publishing', 'researcher_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_constraint(None, 'process_or_technique', type_='foreignkey')
    op.create_foreign_key(op.f('process_or_technique_researcher_id_fkey'), 'process_or_technique', 'researcher', ['researcher_id'], ['id'])
    op.drop_constraint(None, 'patent', type_='foreignkey')
    op.create_foreign_key(op.f('patent_researcher_id_fkey'), 'patent', 'researcher', ['researcher_id'], ['id'])
    op.alter_column('patent', 'researcher_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_constraint(None, 'participation_events', type_='foreignkey')
    op.create_foreign_key(op.f('participation_events_researcher_id_fkey'), 'participation_events', 'researcher', ['researcher_id'], ['id'])
    op.alter_column('participation_events', 'researcher_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_constraint(None, 'other_technical_production', type_='foreignkey')
    op.create_foreign_key(op.f('other_technical_production_researcher_id_fkey'), 'other_technical_production', 'researcher', ['researcher_id'], ['id'])
    op.alter_column('other_technical_production', 'researcher_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_constraint(None, 'mockup', type_='foreignkey')
    op.create_foreign_key(op.f('mockup_researcher_id_fkey'), 'mockup', 'researcher', ['researcher_id'], ['id'])
    op.alter_column('mockup', 'researcher_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_constraint(None, 'maintenance_artistic_work', type_='foreignkey')
    op.create_foreign_key(op.f('maintenance_artistic_work_researcher_id_fkey'), 'maintenance_artistic_work', 'researcher', ['researcher_id'], ['id'])
    op.alter_column('maintenance_artistic_work', 'researcher_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_constraint(None, 'letter_map_or_similar', type_='foreignkey')
    op.create_foreign_key(op.f('letter_map_or_similar_researcher_id_fkey'), 'letter_map_or_similar', 'researcher', ['researcher_id'], ['id'])
    op.alter_column('letter_map_or_similar', 'researcher_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_constraint(None, 'labs', type_='foreignkey')
    op.create_foreign_key(op.f('labs_researcher_id_fkey'), 'labs', 'researcher', ['researcher_id'], ['id'])
    op.alter_column('labs', 'researcher_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_constraint(None, 'industrial_design', type_='foreignkey')
    op.create_foreign_key(op.f('industrial_design_researcher_id_fkey'), 'industrial_design', 'researcher', ['researcher_id'], ['id'])
    op.alter_column('industrial_design', 'researcher_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_constraint(None, 'guidance', type_='foreignkey')
    op.create_foreign_key(op.f('guidance_researcher_id_fkey'), 'guidance', 'researcher', ['researcher_id'], ['id'])
    op.alter_column('guidance', 'researcher_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_constraint(None, 'graduate_program_student', type_='foreignkey')
    op.create_foreign_key(op.f('graduate_program_student_researcher_id_fkey'), 'graduate_program_student', 'researcher', ['researcher_id'], ['id'])
    op.drop_constraint(None, 'foment', type_='foreignkey')
    op.create_foreign_key(op.f('foment_researcher_id_fkey'), 'foment', 'researcher', ['researcher_id'], ['id'])
    op.alter_column('foment', 'researcher_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_constraint(None, 'event_organization', type_='foreignkey')
    op.create_foreign_key(op.f('event_organization_researcher_id_fkey'), 'event_organization', 'researcher', ['researcher_id'], ['id'])
    op.alter_column('event_organization', 'researcher_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_constraint(None, 'education', type_='foreignkey')
    op.create_foreign_key(op.f('education_researcher_id_fkey'), 'education', 'researcher', ['researcher_id'], ['id'])
    op.drop_constraint(None, 'didactic_material', type_='foreignkey')
    op.create_foreign_key(op.f('didactic_material_researcher_id_fkey'), 'didactic_material', 'researcher', ['researcher_id'], ['id'])
    op.drop_constraint(None, 'brand', type_='foreignkey')
    op.create_foreign_key(op.f('brand_researcher_id_fkey'), 'brand', 'researcher', ['researcher_id'], ['id'])
    op.alter_column('brand', 'researcher_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_constraint(None, 'bibliographic_production', type_='foreignkey')
    op.create_foreign_key(op.f('bibliographic_production_researcher_id_fkey'), 'bibliographic_production', 'researcher', ['researcher_id'], ['id'])
    op.alter_column('bibliographic_production', 'researcher_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_constraint(None, 'artistic_production', type_='foreignkey')
    op.create_foreign_key(op.f('artistic_production_researcher_id_fkey'), 'artistic_production', 'researcher', ['researcher_id'], ['id'])
    op.drop_constraint(None, 'advisory_activity', type_='foreignkey')
    op.create_foreign_key(op.f('advisory_activity_researcher_id_fkey'), 'advisory_activity', 'researcher', ['researcher_id'], ['id'])
    # ### end Alembic commands ###
