"""empty message

Revision ID: d0ceb77678ac
Revises: 906555ad3551
Create Date: 2026-06-08 13:03:47.427597

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd0ceb77678ac'
down_revision: Union[str, Sequence[str], None] = '906555ad3551'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'display_name',
               existing_type=sa.VARCHAR(),
               nullable=True,
               schema='admin')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'display_name',
               existing_type=sa.VARCHAR(),
               nullable=False,
               schema='admin')
    # ### end Alembic commands ###
