"""empty message

Revision ID: ebd881ecc239
Revises: 
Create Date: 2026-05-24 17:32:27.295456

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ebd881ecc239'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.execute('CREATE SCHEMA IF NOT EXISTS admin_ufmg')
    op.execute('CREATE SCHEMA IF NOT EXISTS admin')
    op.execute('CREATE SCHEMA IF NOT EXISTS ufmg')
    op.execute('CREATE SCHEMA IF NOT EXISTS logs')
    op.execute('CREATE EXTENSION IF NOT EXISTS unaccent')
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('feedback',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='admin'
    )
    op.create_table('institution',
    sa.Column('institution_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('acronym', sa.String(), nullable=True),
    sa.Column('lattes_id', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('institution_id'),
    sa.UniqueConstraint('acronym'),
    schema='admin'
    )
    op.create_table('newsletter_subscribers',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('subscribed_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    schema='admin'
    )
    op.create_table('researcher',
    sa.Column('researcher_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('lattes_id', sa.String(), nullable=True),
    sa.Column('extra_field', sa.String(), nullable=True),
    sa.Column('status', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('researcher_id'),
    sa.UniqueConstraint('lattes_id'),
    schema='admin'
    )
    op.create_table('roles',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('role'),
    schema='admin'
    )
    op.create_table('department',
    sa.Column('dep_id', sa.String(), nullable=False),
    sa.Column('org_cod', sa.String(), nullable=True),
    sa.Column('dep_nom', sa.String(), nullable=True),
    sa.Column('dep_des', sa.Text(), nullable=True),
    sa.Column('dep_email', sa.String(), nullable=True),
    sa.Column('dep_site', sa.String(), nullable=True),
    sa.Column('dep_sigla', sa.String(), nullable=True),
    sa.Column('dep_tel', sa.String(), nullable=True),
    sa.Column('img_data', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('dep_id'),
    schema='admin_ufmg'
    )
    op.create_table('technician',
    sa.Column('technician_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('full_name', sa.String(), nullable=True),
    sa.Column('gender', sa.String(), nullable=True),
    sa.Column('status_code', sa.String(), nullable=True),
    sa.Column('work_regime', sa.String(), nullable=True),
    sa.Column('job_class', sa.String(), nullable=True),
    sa.Column('job_title', sa.String(), nullable=True),
    sa.Column('job_rank', sa.String(), nullable=True),
    sa.Column('job_reference_code', sa.String(), nullable=True),
    sa.Column('academic_degree', sa.String(), nullable=True),
    sa.Column('organization_entry_date', sa.Date(), nullable=True),
    sa.Column('last_promotion_date', sa.Date(), nullable=True),
    sa.Column('employment_status_description', sa.String(), nullable=True),
    sa.Column('department_name', sa.String(), nullable=True),
    sa.Column('career_category', sa.String(), nullable=True),
    sa.Column('academic_unit', sa.String(), nullable=True),
    sa.Column('unit_code', sa.String(), nullable=True),
    sa.Column('function_code', sa.String(), nullable=True),
    sa.Column('position_code', sa.String(), nullable=True),
    sa.Column('leadership_start_date', sa.Date(), nullable=True),
    sa.Column('leadership_end_date', sa.Date(), nullable=True),
    sa.Column('current_function_name', sa.String(), nullable=True),
    sa.Column('function_location', sa.String(), nullable=True),
    sa.Column('registration_number', sa.String(), nullable=True),
    sa.Column('ufmg_registration_number', sa.String(), nullable=True),
    sa.Column('semester_reference', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('technician_id'),
    schema='admin_ufmg'
    )
    op.create_table('country',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('name_pt', sa.String(), nullable=False),
    sa.Column('alpha_2_code', sa.String(length=2), nullable=True),
    sa.Column('alpha_3_code', sa.String(length=3), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('alpha_2_code'),
    sa.UniqueConstraint('alpha_3_code'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('name_pt')
    )
    op.create_table('graduate_program_ind_prod',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('graduate_program_id', sa.UUID(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('ind_prod_article', sa.Float(), nullable=True),
    sa.Column('ind_prod_book', sa.Float(), nullable=True),
    sa.Column('ind_prod_book_chapter', sa.Float(), nullable=True),
    sa.Column('ind_prod_software', sa.Float(), nullable=True),
    sa.Column('ind_prod_report', sa.Float(), nullable=True),
    sa.Column('ind_prod_granted_patent', sa.Float(), nullable=True),
    sa.Column('ind_prod_not_granted_patent', sa.Float(), nullable=True),
    sa.Column('ind_prod_guidance', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('great_area_expertise',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('institution',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('acronym', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('lattes_id', sa.String(), nullable=True),
    sa.Column('cnpj', sa.String(), nullable=True),
    sa.Column('image', sa.String(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('acronym'),
    sa.UniqueConstraint('cnpj'),
    sa.UniqueConstraint('name')
    )
    op.create_table('jcr',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('rank', sa.String(), nullable=True),
    sa.Column('journalname', sa.String(), nullable=True),
    sa.Column('jcryear', sa.String(), nullable=True),
    sa.Column('abbrjournal', sa.String(), nullable=True),
    sa.Column('issn', sa.String(), nullable=True),
    sa.Column('eissn', sa.String(), nullable=True),
    sa.Column('totalcites', sa.String(), nullable=True),
    sa.Column('totalarticles', sa.String(), nullable=True),
    sa.Column('citableitems', sa.String(), nullable=True),
    sa.Column('citedhalflife', sa.String(), nullable=True),
    sa.Column('citinghalflife', sa.String(), nullable=True),
    sa.Column('jif2019', sa.Float(), nullable=True),
    sa.Column('url_revista', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('routine',
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('error', sa.Boolean(), nullable=True),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('type'),
    schema='logs'
    )
    op.create_table('periodical_magazine',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('issn', sa.String(), nullable=True),
    sa.Column('qualis', sa.String(), nullable=True),
    sa.Column('jcr', sa.String(), nullable=True),
    sa.Column('jcr_link', sa.String(), nullable=True),
    sa.Column('reference_period', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('research_dictionary',
    sa.Column('research_dictionary_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('term', sa.String(), nullable=True),
    sa.Column('frequency', sa.Integer(), nullable=True),
    sa.Column('type_', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('research_dictionary_id')
    )
    op.create_table('research_group',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('institution', sa.String(), nullable=True),
    sa.Column('first_leader', sa.String(), nullable=True),
    sa.Column('first_leader_id', sa.UUID(), nullable=True),
    sa.Column('second_leader', sa.String(), nullable=True),
    sa.Column('second_leader_id', sa.UUID(), nullable=True),
    sa.Column('area', sa.String(), nullable=True),
    sa.Column('census', sa.Integer(), nullable=True),
    sa.Column('start_of_collection', sa.String(), nullable=True),
    sa.Column('end_of_collection', sa.String(), nullable=True),
    sa.Column('group_identifier', sa.String(), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('institution_name', sa.String(), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('group_identifier'),
    sa.UniqueConstraint('name', 'institution', name='uq_research_group_name_institution')
    )
    op.create_table('sdg',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('seeder_versions',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('table_name', sa.String(), nullable=False),
    sa.Column('executed_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('table_name')
    )
    op.create_table('departament',
    sa.Column('dep_id', sa.String(), nullable=False),
    sa.Column('org_cod', sa.String(), nullable=True),
    sa.Column('dep_nom', sa.String(), nullable=True),
    sa.Column('dep_des', sa.Text(), nullable=True),
    sa.Column('dep_email', sa.String(), nullable=True),
    sa.Column('dep_site', sa.Text(), nullable=True),
    sa.Column('dep_sigla', sa.String(), nullable=True),
    sa.Column('dep_tel', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('dep_id'),
    schema='ufmg'
    )
    op.create_table('departament_researcher',
    sa.Column('dep_id', sa.String(), nullable=False),
    sa.Column('researcher_id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('dep_id', 'researcher_id'),
    schema='ufmg'
    )
    op.create_table('mandate',
    sa.Column('member', sa.String(), nullable=False),
    sa.Column('departament', sa.String(), nullable=False),
    sa.Column('mandate', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('member', 'departament'),
    schema='ufmg'
    )
    op.create_table('researcher',
    sa.Column('researcher_id', sa.Uuid(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=True),
    sa.Column('gender', sa.String(), nullable=True),
    sa.Column('status_code', sa.String(), nullable=True),
    sa.Column('work_regime', sa.String(), nullable=True),
    sa.Column('job_class', sa.String(), nullable=True),
    sa.Column('job_title', sa.String(), nullable=True),
    sa.Column('job_rank', sa.String(), nullable=True),
    sa.Column('job_reference_code', sa.String(), nullable=True),
    sa.Column('academic_degree', sa.String(), nullable=True),
    sa.Column('organization_entry_date', sa.Date(), nullable=True),
    sa.Column('last_promotion_date', sa.Date(), nullable=True),
    sa.Column('employment_status_description', sa.String(), nullable=True),
    sa.Column('department_name', sa.String(), nullable=True),
    sa.Column('career_category', sa.String(), nullable=True),
    sa.Column('academic_unit', sa.String(), nullable=True),
    sa.Column('unit_code', sa.String(), nullable=True),
    sa.Column('function_code', sa.String(), nullable=True),
    sa.Column('position_code', sa.String(), nullable=True),
    sa.Column('leadership_start_date', sa.Date(), nullable=True),
    sa.Column('leadership_end_date', sa.Date(), nullable=True),
    sa.Column('current_function_name', sa.String(), nullable=True),
    sa.Column('function_location', sa.String(), nullable=True),
    sa.Column('registration_number', sa.String(), nullable=True),
    sa.Column('ufmg_registration_number', sa.String(), nullable=True),
    sa.Column('semester_reference', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('researcher_id'),
    schema='ufmg'
    )
    op.create_table('researcher_data',
    sa.Column('cpf', sa.String(), nullable=False),
    sa.Column('nome', sa.String(), nullable=True),
    sa.Column('classe', sa.Integer(), nullable=True),
    sa.Column('nivel', sa.Integer(), nullable=True),
    sa.Column('inicio', sa.DateTime(), nullable=True),
    sa.Column('fim', sa.DateTime(), nullable=True),
    sa.Column('tempo_nivel', sa.Integer(), nullable=True),
    sa.Column('tempo_acumulado', sa.Integer(), nullable=True),
    sa.Column('arquivo', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('cpf'),
    schema='ufmg'
    )
    op.create_table('technician',
    sa.Column('technician_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('full_name', sa.String(), nullable=True),
    sa.Column('gender', sa.String(), nullable=True),
    sa.Column('status_code', sa.String(), nullable=True),
    sa.Column('work_regime', sa.String(), nullable=True),
    sa.Column('job_class', sa.String(), nullable=True),
    sa.Column('job_title', sa.String(), nullable=True),
    sa.Column('job_rank', sa.String(), nullable=True),
    sa.Column('job_reference_code', sa.String(), nullable=True),
    sa.Column('academic_degree', sa.String(), nullable=True),
    sa.Column('organization_entry_date', sa.Date(), nullable=True),
    sa.Column('last_promotion_date', sa.Date(), nullable=True),
    sa.Column('employment_status_description', sa.String(), nullable=True),
    sa.Column('department_name', sa.String(), nullable=True),
    sa.Column('career_category', sa.String(), nullable=True),
    sa.Column('academic_unit', sa.String(), nullable=True),
    sa.Column('unit_code', sa.String(), nullable=True),
    sa.Column('function_code', sa.String(), nullable=True),
    sa.Column('position_code', sa.String(), nullable=True),
    sa.Column('leadership_start_date', sa.Date(), nullable=True),
    sa.Column('leadership_end_date', sa.Date(), nullable=True),
    sa.Column('current_function_name', sa.String(), nullable=True),
    sa.Column('function_location', sa.String(), nullable=True),
    sa.Column('registration_number', sa.String(), nullable=True),
    sa.Column('ufmg_registration_number', sa.String(), nullable=True),
    sa.Column('semester_reference', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('technician_id'),
    schema='ufmg'
    )
    op.create_table('graduate_program',
    sa.Column('graduate_program_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('area', sa.String(), nullable=False),
    sa.Column('modality', sa.String(), nullable=False),
    sa.Column('institution_id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(), nullable=True),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('rating', sa.String(), nullable=True),
    sa.Column('state', sa.String(), nullable=True),
    sa.Column('city', sa.String(), nullable=True),
    sa.Column('region', sa.String(), nullable=True),
    sa.Column('url_image', sa.String(), nullable=True),
    sa.Column('acronym', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('visible', sa.Boolean(), nullable=True),
    sa.Column('site', sa.Text(), nullable=True),
    sa.Column('menagers', sa.ARRAY(sa.String()), nullable=True),
    sa.ForeignKeyConstraint(['institution_id'], ['admin.institution.institution_id'], ),
    sa.PrimaryKeyConstraint('graduate_program_id'),
    sa.UniqueConstraint('code'),
    schema='admin'
    )
    op.create_table('permission',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('role_id', sa.UUID(), nullable=False),
    sa.Column('permission', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['admin.roles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='admin'
    )
    op.create_table('researcher_institution',
    sa.Column('researcher_institution_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('researcher_id', sa.UUID(), nullable=False),
    sa.Column('institution_id', sa.UUID(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('is_current', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['institution_id'], ['admin.institution.institution_id'], ),
    sa.ForeignKeyConstraint(['researcher_id'], ['admin.researcher.researcher_id'], ),
    sa.PrimaryKeyConstraint('researcher_institution_id'),
    schema='admin'
    )
    op.create_table('users',
    sa.Column('user_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('display_name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('uid', sa.String(), nullable=False),
    sa.Column('photo_url', sa.Text(), nullable=True),
    sa.Column('lattes_id', sa.String(), nullable=True),
    sa.Column('institution_id', sa.UUID(), nullable=True),
    sa.Column('provider', sa.String(), nullable=True),
    sa.Column('linkedin', sa.String(), nullable=True),
    sa.Column('verify', sa.Boolean(), nullable=True),
    sa.Column('shib_id', sa.String(), nullable=True),
    sa.Column('shib_code', sa.String(), nullable=True),
    sa.Column('birth_date', sa.String(), nullable=True),
    sa.Column('course_level', sa.String(), nullable=True),
    sa.Column('first_name', sa.String(), nullable=True),
    sa.Column('registration', sa.String(), nullable=True),
    sa.Column('gender', sa.String(), nullable=True),
    sa.Column('last_name', sa.String(), nullable=True),
    sa.Column('email_status', sa.String(), nullable=True),
    sa.Column('visible_email', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['institution_id'], ['admin.institution.institution_id'], ),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('uid'),
    schema='admin'
    )
    op.create_table('weights',
    sa.Column('institution_id', sa.UUID(), nullable=False),
    sa.Column('a1', sa.Float(), nullable=True),
    sa.Column('a2', sa.Float(), nullable=True),
    sa.Column('a3', sa.Float(), nullable=True),
    sa.Column('a4', sa.Float(), nullable=True),
    sa.Column('b1', sa.Float(), nullable=True),
    sa.Column('b2', sa.Float(), nullable=True),
    sa.Column('b3', sa.Float(), nullable=True),
    sa.Column('b4', sa.Float(), nullable=True),
    sa.Column('c', sa.Float(), nullable=True),
    sa.Column('sq', sa.Float(), nullable=True),
    sa.Column('book', sa.Float(), nullable=True),
    sa.Column('book_chapter', sa.Float(), nullable=True),
    sa.Column('software', sa.String(), nullable=True),
    sa.Column('patent_granted', sa.String(), nullable=True),
    sa.Column('patent_not_granted', sa.String(), nullable=True),
    sa.Column('report', sa.String(), nullable=True),
    sa.Column('f1', sa.Float(), nullable=True),
    sa.Column('f2', sa.Float(), nullable=True),
    sa.Column('f3', sa.Float(), nullable=True),
    sa.Column('f4', sa.Float(), nullable=True),
    sa.Column('f5', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['institution_id'], ['admin.institution.institution_id'], ),
    sa.PrimaryKeyConstraint('institution_id'),
    schema='admin'
    )
    op.create_table('department_researcher',
    sa.Column('dep_id', sa.String(), nullable=False),
    sa.Column('researcher_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['dep_id'], ['admin_ufmg.department.dep_id'], ),
    sa.ForeignKeyConstraint(['researcher_id'], ['admin.researcher.researcher_id'], ),
    sa.PrimaryKeyConstraint('dep_id', 'researcher_id'),
    schema='admin_ufmg'
    )
    op.create_table('department_technician',
    sa.Column('dep_id', sa.String(), nullable=False),
    sa.Column('technician_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['dep_id'], ['admin_ufmg.department.dep_id'], ),
    sa.ForeignKeyConstraint(['technician_id'], ['admin_ufmg.technician.technician_id'], ),
    sa.PrimaryKeyConstraint('dep_id', 'technician_id'),
    schema='admin_ufmg'
    )
    op.create_table('disciplines',
    sa.Column('discipline_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('dep_id', sa.String(), nullable=True),
    sa.Column('semester', sa.String(), nullable=True),
    sa.Column('department', sa.String(), nullable=True),
    sa.Column('academic_activity_code', sa.String(), nullable=True),
    sa.Column('academic_activity_name', sa.String(), nullable=True),
    sa.Column('academic_activity_ch', sa.String(), nullable=True),
    sa.Column('demanding_courses', sa.String(), nullable=True),
    sa.Column('oft', sa.String(), nullable=True),
    sa.Column('available_slots', sa.String(), nullable=True),
    sa.Column('occupied_slots', sa.String(), nullable=True),
    sa.Column('percent_occupied_slots', sa.String(), nullable=True),
    sa.Column('schedule', sa.String(), nullable=True),
    sa.Column('language', sa.String(), nullable=True),
    sa.Column('researcher_id', sa.ARRAY(sa.UUID()), nullable=True),
    sa.Column('researcher_name', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('workload', sa.ARRAY(sa.String()), nullable=True),
    sa.ForeignKeyConstraint(['dep_id'], ['admin_ufmg.department.dep_id'], ),
    sa.PrimaryKeyConstraint('discipline_id'),
    schema='admin_ufmg'
    )
    op.create_table('researcher',
    sa.Column('researcher_id', sa.UUID(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=True),
    sa.Column('gender', sa.String(), nullable=True),
    sa.Column('status_code', sa.String(), nullable=True),
    sa.Column('work_regime', sa.String(), nullable=True),
    sa.Column('job_class', sa.String(), nullable=True),
    sa.Column('job_title', sa.String(), nullable=True),
    sa.Column('job_rank', sa.String(), nullable=True),
    sa.Column('job_reference_code', sa.String(), nullable=True),
    sa.Column('academic_degree', sa.String(), nullable=True),
    sa.Column('organization_entry_date', sa.Date(), nullable=True),
    sa.Column('last_promotion_date', sa.Date(), nullable=True),
    sa.Column('employment_status_description', sa.String(), nullable=True),
    sa.Column('department_name', sa.String(), nullable=True),
    sa.Column('career_category', sa.String(), nullable=True),
    sa.Column('academic_unit', sa.String(), nullable=True),
    sa.Column('unit_code', sa.String(), nullable=True),
    sa.Column('function_code', sa.String(), nullable=True),
    sa.Column('position_code', sa.String(), nullable=True),
    sa.Column('leadership_start_date', sa.Date(), nullable=True),
    sa.Column('leadership_end_date', sa.Date(), nullable=True),
    sa.Column('current_function_name', sa.String(), nullable=True),
    sa.Column('function_location', sa.String(), nullable=True),
    sa.Column('registration_number', sa.String(), nullable=True),
    sa.Column('ufmg_registration_number', sa.String(), nullable=True),
    sa.Column('semester_reference', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['researcher_id'], ['admin.researcher.researcher_id'], ),
    sa.PrimaryKeyConstraint('researcher_id'),
    schema='admin_ufmg'
    )
    op.create_table('area_expertise',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('great_area_expertise_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['great_area_expertise_id'], ['great_area_expertise.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('graduate_program',
    sa.Column('graduate_program_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('area', sa.String(), nullable=False),
    sa.Column('modality', sa.String(), nullable=False),
    sa.Column('institution_id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(), nullable=True),
    sa.Column('name_en', sa.String(), nullable=True),
    sa.Column('basic_area', sa.String(), nullable=True),
    sa.Column('cooperation_project', sa.String(), nullable=True),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('rating', sa.String(), nullable=True),
    sa.Column('state', sa.String(), nullable=True),
    sa.Column('city', sa.String(), nullable=True),
    sa.Column('region', sa.String(), nullable=True),
    sa.Column('url_image', sa.String(), nullable=True),
    sa.Column('acronym', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('visible', sa.Boolean(), nullable=True),
    sa.Column('site', sa.Text(), nullable=True),
    sa.Column('coordinator', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('start', sa.Date(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('periodicity', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['institution_id'], ['institution.id'], ),
    sa.PrimaryKeyConstraint('graduate_program_id')
    )
    op.create_table('research_lines',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('research_group_id', sa.UUID(), nullable=True),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('objective', sa.Text(), nullable=True),
    sa.Column('keyword', sa.String(), nullable=True),
    sa.Column('group_identifier', sa.String(), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('predominant_major_area', sa.String(), nullable=True),
    sa.Column('predominant_area', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['research_group_id'], ['research_group.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sdg_alignment',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('reference_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('sdg_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['sdg_id'], ['sdg.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('state',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('country_id', sa.UUID(), nullable=False),
    sa.Column('abbreviation', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['country_id'], ['country.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('abbreviation'),
    sa.UniqueConstraint('name')
    )
    op.create_table('departament_technician',
    sa.Column('dep_id', sa.String(), nullable=False),
    sa.Column('technician_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['dep_id'], ['ufmg.departament.dep_id'], ),
    sa.ForeignKeyConstraint(['technician_id'], ['ufmg.technician.technician_id'], ),
    sa.PrimaryKeyConstraint('dep_id', 'technician_id'),
    schema='ufmg'
    )
    op.create_table('graduate_program_researcher',
    sa.Column('graduate_program_id', sa.UUID(), nullable=False),
    sa.Column('researcher_id', sa.UUID(), nullable=False),
    sa.Column('year', sa.ARRAY(sa.Integer()), nullable=True),
    sa.Column('type_', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['graduate_program_id'], ['admin.graduate_program.graduate_program_id'], ),
    sa.ForeignKeyConstraint(['researcher_id'], ['admin.researcher.researcher_id'], ),
    sa.PrimaryKeyConstraint('graduate_program_id', 'researcher_id'),
    schema='admin'
    )
    op.create_table('graduate_program_student',
    sa.Column('graduate_program_id', sa.UUID(), nullable=False),
    sa.Column('researcher_id', sa.UUID(), nullable=False),
    sa.Column('year', sa.ARRAY(sa.Integer()), nullable=False),
    sa.ForeignKeyConstraint(['graduate_program_id'], ['admin.graduate_program.graduate_program_id'], ),
    sa.ForeignKeyConstraint(['researcher_id'], ['admin.researcher.researcher_id'], ),
    sa.PrimaryKeyConstraint('graduate_program_id', 'researcher_id', 'year'),
    schema='admin'
    )
    op.create_table('users_roles',
    sa.Column('role_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['admin.roles.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['admin.users.user_id'], ),
    sa.PrimaryKeyConstraint('role_id', 'user_id'),
    schema='admin'
    )
    op.create_table('city',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('country_id', sa.UUID(), nullable=False),
    sa.Column('state_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['country_id'], ['country.id'], ),
    sa.ForeignKeyConstraint(['state_id'], ['state.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('research_lines_programs',
    sa.Column('graduate_program_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('area', sa.String(), nullable=False),
    sa.Column('start_year', sa.Integer(), nullable=True),
    sa.Column('end_year', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['graduate_program_id'], ['graduate_program.graduate_program_id'], ),
    sa.PrimaryKeyConstraint('graduate_program_id', 'name')
    )
    op.create_table('sub_area_expertise',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('area_expertise_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['area_expertise_id'], ['area_expertise.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('area_specialty',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('sub_area_expertise_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['sub_area_expertise_id'], ['sub_area_expertise.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('researcher',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('lattes_id', sa.String(), nullable=True),
    sa.Column('lattes_10_id', sa.String(), nullable=True),
    sa.Column('last_update', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('has_image', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('citations', sa.String(), nullable=True),
    sa.Column('orcid', sa.String(), nullable=True),
    sa.Column('abstract', sa.Text(), nullable=True),
    sa.Column('abstract_en', sa.Text(), nullable=True),
    sa.Column('abstract_ai', sa.Text(), nullable=True),
    sa.Column('other_information', sa.String(), nullable=True),
    sa.Column('city_id', sa.UUID(), nullable=True),
    sa.Column('country_id', sa.UUID(), nullable=True),
    sa.Column('qtt_publications', sa.Integer(), nullable=True),
    sa.Column('institution_id', sa.UUID(), nullable=True),
    sa.Column('graduate_program', sa.String(), nullable=True),
    sa.Column('graduation', sa.String(), nullable=True),
    sa.Column('status', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('classification', sa.String(), nullable=True),
    sa.Column('stars', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('update_abstract', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['city_id'], ['city.id'], ),
    sa.ForeignKeyConstraint(['country_id'], ['country.id'], ),
    sa.ForeignKeyConstraint(['institution_id'], ['institution.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('lattes_10_id'),
    sa.UniqueConstraint('lattes_id')
    )
    op.create_table('advisory_activity',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('researcher_id', sa.UUID(), nullable=False),
    sa.Column('organ_name', sa.String(), nullable=True),
    sa.Column('start_year', sa.String(), nullable=True),
    sa.Column('sequence_id', sa.Integer(), nullable=True),
    sa.Column('organ_code', sa.String(), nullable=True),
    sa.Column('unit_code', sa.String(), nullable=True),
    sa.Column('unit_name', sa.String(), nullable=True),
    sa.Column('specification', sa.Text(), nullable=True),
    sa.Column('is_current', sa.String(), nullable=True),
    sa.Column('start_month', sa.String(), nullable=True),
    sa.Column('end_month', sa.String(), nullable=True),
    sa.Column('end_year', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['researcher_id'], ['researcher.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('artistic_production',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('researcher_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('type', sa.Text(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['researcher_id'], ['researcher.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bibliographic_production',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('title_en', sa.String(), nullable=True),
    sa.Column('doi', sa.String(), nullable=True),
    sa.Column('nature', sa.String(), nullable=True),
    sa.Column('year', sa.String(), nullable=True),
    sa.Column('country_id', sa.UUID(), nullable=True),
    sa.Column('language', sa.String(), nullable=True),
    sa.Column('means_divulgation', sa.String(), nullable=True),
    sa.Column('homepage', sa.String(), nullable=True),
    sa.Column('relevance', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('has_image', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('scientific_divulgation', sa.Boolean(), nullable=True),
    sa.Column('researcher_id', sa.UUID(), nullable=True),
    sa.Column('authors', sa.String(), nullable=True),
    sa.Column('year_', sa.Integer(), nullable=True),
    sa.Column('is_new', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['country_id'], ['country.id'], ),
    sa.ForeignKeyConstraint(['researcher_id'], ['researcher.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('brand',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('relevance', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('has_image', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('goal', sa.String(), nullable=True),
    sa.Column('nature', sa.String(), nullable=True),
    sa.Column('researcher_id', sa.UUID(), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('is_new', sa.Boolean(), server_default=sa.text('true'), nullable=True),
    sa.Column('stars', sa.Integer(), server_default=sa.text('0'), nullable=True),
    sa.ForeignKeyConstraint(['researcher_id'], ['researcher.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('didactic_material',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('researcher_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('country', sa.String(), nullable=True),
    sa.Column('nature', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['researcher_id'], ['researcher.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('education',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('researcher_id', sa.UUID(), nullable=False),
    sa.Column('degree', sa.String(), nullable=False),
    sa.Column('education_name', sa.String(), nullable=True),
    sa.Column('education_start', sa.Integer(), nullable=True),
    sa.Column('education_end', sa.Integer(), nullable=True),
    sa.Column('key_words', sa.String(), nullable=True),
    sa.Column('institution', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['researcher_id'], ['researcher.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('event_organization',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('promoter_institution', sa.String(), nullable=True),
    sa.Column('nature', sa.String(), nullable=True),
    sa.Column('researcher_id', sa.UUID(), nullable=True),
    sa.Column('local', sa.String(), nullable=True),
    sa.Column('duration_in_weeks', sa.Integer(), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('is_new', sa.Boolean(), server_default=sa.text('true'), nullable=True),
    sa.ForeignKeyConstraint(['researcher_id'], ['researcher.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('foment',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('researcher_id', sa.UUID(), nullable=True),
    sa.Column('modality_code', sa.String(), nullable=True),
    sa.Column('modality_name', sa.String(), nullable=True),
    sa.Column('call_title', sa.String(), nullable=True),
    sa.Column('category_level_code', sa.String(), nullable=True),
    sa.Column('funding_program_name', sa.String(), nullable=True),
    sa.Column('institute_name', sa.String(), nullable=True),
    sa.Column('aid_quantity', sa.Integer(), nullable=True),
    sa.Column('scholarship_quantity', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['researcher_id'], ['researcher.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('graduate_program_researcher',
    sa.Column('graduate_program_id', sa.UUID(), nullable=False),
    sa.Column('researcher_id', sa.UUID(), nullable=False),
    sa.Column('year', sa.ARRAY(sa.Integer()), nullable=True),
    sa.Column('type_', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['graduate_program_id'], ['graduate_program.graduate_program_id'], ),
    sa.ForeignKeyConstraint(['researcher_id'], ['researcher.id'], ),
    sa.PrimaryKeyConstraint('graduate_program_id', 'researcher_id')
    )
    op.create_table('graduate_program_student',
    sa.Column('graduate_program_id', sa.UUID(), nullable=False),
    sa.Column('researcher_id', sa.UUID(), nullable=False),
    sa.Column('year', sa.ARRAY(sa.Integer()), nullable=False),
    sa.ForeignKeyConstraint(['graduate_program_id'], ['graduate_program.graduate_program_id'], ),
    sa.ForeignKeyConstraint(['researcher_id'], ['researcher.id'], ),
    sa.PrimaryKeyConstraint('graduate_program_id', 'researcher_id', 'year')
    )
    op.create_table('guidance',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('researcher_id', sa.UUID(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('nature', sa.String(), nullable=True),
    sa.Column('oriented', sa.String(), nullable=True),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('is_new', sa.Boolean(), server_default=sa.text('true'), nullable=True),
    sa.Column('stars', sa.Integer(), server_default=sa.text('0'), nullable=True),
    sa.ForeignKeyConstraint(['researcher_id'], ['researcher.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('industrial_design',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('researcher_id', sa.UUID(), nullable=True),
    sa.Column('production_sequence', sa.Integer(), nullable=True),
    sa.Column('title_en', sa.String(), nullable=True),
    sa.Column('year', sa.String(), nullable=True),
    sa.Column('country', sa.String(), nullable=True),
    sa.Column('language', sa.String(), nullable=True),
    sa.Column('dissemination_medium', sa.String(), nullable=True),
    sa.Column('homepage', sa.String(), nullable=True),
    sa.Column('doi', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['researcher_id'], ['researcher.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('labs',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('hashed_id', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('location', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('website', sa.Text(), nullable=True),
    sa.Column('activities', sa.Text(), nullable=True),
    sa.Column('areas', sa.Text(), nullable=True),
    sa.Column('campus', sa.Text(), nullable=True),
    sa.Column('institution_id', sa.UUID(), nullable=True),
    sa.Column('researcher_id', sa.UUID(), nullable=True),
    sa.Column('responsible', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['institution_id'], ['institution.id'], ),
    sa.ForeignKeyConstraint(['researcher_id'], ['researcher.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('letter_map_or_similar',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('researcher_id', sa.UUID(), nullable=True),
    sa.Column('production_sequence', sa.Integer(), nullable=True),
    sa.Column('title_en', sa.String(), nullable=True),
    sa.Column('year', sa.String(), nullable=True),
    sa.Column('country', sa.String(), nullable=True),
    sa.Column('language', sa.String(), nullable=True),
    sa.Column('dissemination_medium', sa.String(), nullable=True),
    sa.Column('homepage', sa.String(), nullable=True),
    sa.Column('doi', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['researcher_id'], ['researcher.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('maintenance_artistic_work',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('researcher_id', sa.UUID(), nullable=True),
    sa.Column('production_sequence', sa.Integer(), nullable=True),
    sa.Column('title_en', sa.String(), nullable=True),
    sa.Column('year', sa.String(), nullable=True),
    sa.Column('country', sa.String(), nullable=True),
    sa.Column('language', sa.String(), nullable=True),
    sa.Column('dissemination_medium', sa.String(), nullable=True),
    sa.Column('homepage', sa.String(), nullable=True),
    sa.Column('doi', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['researcher_id'], ['researcher.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mockup',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('researcher_id', sa.UUID(), nullable=True),
    sa.Column('production_sequence', sa.Integer(), nullable=True),
    sa.Column('title_en', sa.String(), nullable=True),
    sa.Column('year', sa.String(), nullable=True),
    sa.Column('country', sa.String(), nullable=True),
    sa.Column('language', sa.String(), nullable=True),
    sa.Column('dissemination_medium', sa.String(), nullable=True),
    sa.Column('homepage', sa.String(), nullable=True),
    sa.Column('doi', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['researcher_id'], ['researcher.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('openalex_researcher',
    sa.Column('researcher_id', sa.UUID(), nullable=False),
    sa.Column('h_index', sa.Integer(), nullable=True),
    sa.Column('relevance_score', sa.Float(), nullable=True),
    sa.Column('works_count', sa.Integer(), nullable=True),
    sa.Column('cited_by_count', sa.Integer(), nullable=True),
    sa.Column('i10_index', sa.Integer(), nullable=True),
    sa.Column('scopus', sa.String(length=255), nullable=True),
    sa.Column('orcid', sa.String(length=255), nullable=True),
    sa.Column('openalex', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['researcher_id'], ['researcher.id'], ),
    sa.PrimaryKeyConstraint('researcher_id')
    )
    op.create_table('other_technical_production',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('researcher_id', sa.UUID(), nullable=True),
    sa.Column('production_sequence', sa.Integer(), nullable=True),
    sa.Column('title_en', sa.String(), nullable=True),
    sa.Column('year', sa.String(), nullable=True),
    sa.Column('country', sa.String(), nullable=True),
    sa.Column('language', sa.String(), nullable=True),
    sa.Column('dissemination_medium', sa.String(), nullable=True),
    sa.Column('homepage', sa.String(), nullable=True),
    sa.Column('doi', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['researcher_id'], ['researcher.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('participation_events',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('event_name', sa.String(), nullable=True),
    sa.Column('nature', sa.String(), nullable=True),
    sa.Column('form_participation', sa.String(), nullable=True),
    sa.Column('type_participation', sa.String(), nullable=True),
    sa.Column('researcher_id', sa.UUID(), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('is_new', sa.Boolean(), server_default=sa.text('true'), nullable=True),
    sa.Column('stars', sa.Integer(), server_default=sa.text('0'), nullable=True),
    sa.ForeignKeyConstraint(['researcher_id'], ['researcher.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('patent',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('relevance', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('has_image', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('development_year', sa.String(), nullable=True),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('researcher_id', sa.UUID(), nullable=True),
    sa.Column('code', sa.String(), nullable=True),
    sa.Column('grant_date', sa.DateTime(), nullable=True),
    sa.Column('deposit_date', sa.String(), nullable=True),
    sa.Column('is_new', sa.Boolean(), server_default=sa.text('true'), nullable=True),
    sa.Column('stars', sa.Integer(), server_default=sa.text('0'), nullable=True),
    sa.ForeignKeyConstraint(['researcher_id'], ['researcher.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('process_or_technique',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('researcher_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('sequence_id', sa.Integer(), nullable=True),
    sa.Column('nature', sa.String(), nullable=True),
    sa.Column('title_en', sa.Text(), nullable=True),
    sa.Column('year', sa.String(), nullable=True),
    sa.Column('country', sa.String(), nullable=True),
    sa.Column('language', sa.String(), nullable=True),
    sa.Column('dissemination_medium', sa.String(), nullable=True),
    sa.Column('home_page', sa.Text(), nullable=True),
    sa.Column('doi', sa.String(), nullable=True),
    sa.Column('is_relevant', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('has_innovation_potential', sa.String(), nullable=True),
    sa.Column('purpose', sa.Text(), nullable=True),
    sa.Column('purpose_en', sa.Text(), nullable=True),
    sa.Column('availability', sa.String(), nullable=True),
    sa.Column('funding_institution', sa.String(), nullable=True),
    sa.Column('city', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['researcher_id'], ['researcher.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('publishing',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('researcher_id', sa.UUID(), nullable=True),
    sa.Column('production_sequence', sa.Integer(), nullable=True),
    sa.Column('title_en', sa.String(), nullable=True),
    sa.Column('year', sa.String(), nullable=True),
    sa.Column('country', sa.String(), nullable=True),
    sa.Column('language', sa.String(), nullable=True),
    sa.Column('dissemination_medium', sa.String(), nullable=True),
    sa.Column('homepage', sa.String(), nullable=True),
    sa.Column('doi', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['researcher_id'], ['researcher.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('radio_or_tv_program',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('researcher_id', sa.UUID(), nullable=True),
    sa.Column('production_sequence', sa.Integer(), nullable=True),
    sa.Column('title_en', sa.String(), nullable=True),
    sa.Column('year', sa.String(), nullable=True),
    sa.Column('country', sa.String(), nullable=True),
    sa.Column('language', sa.String(), nullable=True),
    sa.Column('dissemination_medium', sa.String(), nullable=True),
    sa.Column('homepage', sa.String(), nullable=True),
    sa.Column('doi', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['researcher_id'], ['researcher.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('registered_cultivar',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('researcher_id', sa.UUID(), nullable=False),
    sa.Column('denomination', sa.String(), nullable=True),
    sa.Column('denomination_en', sa.String(), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('country', sa.String(), nullable=True),
    sa.Column('code', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['researcher_id'], ['researcher.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('relevant_production',
    sa.Column('researcher_id', sa.UUID(), nullable=False),
    sa.Column('production_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('has_image', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['researcher_id'], ['researcher.id'], ),
    sa.PrimaryKeyConstraint('researcher_id', 'production_id', 'type')
    )
    op.create_table('research_group_researcher',
    sa.Column('research_group_id', sa.UUID(), nullable=False),
    sa.Column('researcher_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['research_group_id'], ['research_group.id'], ),
    sa.ForeignKeyConstraint(['researcher_id'], ['researcher.id'], ),
    sa.PrimaryKeyConstraint('research_group_id', 'researcher_id')
    )
    op.create_table('research_project',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('researcher_id', sa.UUID(), nullable=False),
    sa.Column('start_year', sa.Integer(), nullable=True),
    sa.Column('end_year', sa.Integer(), nullable=True),
    sa.Column('agency_code', sa.String(), nullable=True),
    sa.Column('agency_name', sa.String(), nullable=True),
    sa.Column('project_name', sa.Text(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('nature', sa.String(), nullable=True),
    sa.Column('number_undergraduates', sa.Integer(), server_default=sa.text('0'), nullable=True),
    sa.Column('number_specialists', sa.Integer(), server_default=sa.text('0'), nullable=True),
    sa.Column('number_academic_masters', sa.Integer(), server_default=sa.text('0'), nullable=True),
    sa.Column('number_phd', sa.Integer(), server_default=sa.text('0'), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('stars', sa.Integer(), server_default=sa.text('0'), nullable=True),
    sa.ForeignKeyConstraint(['researcher_id'], ['researcher.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('research_report',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('researcher_id', sa.UUID(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('project_name', sa.String(), nullable=True),
    sa.Column('financing_institutionc', sa.String(), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('is_new', sa.Boolean(), server_default=sa.text('true'), nullable=True),
    sa.Column('stars', sa.Integer(), server_default=sa.text('0'), nullable=True),
    sa.ForeignKeyConstraint(['researcher_id'], ['researcher.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('researcher_address',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('researcher_id', sa.UUID(), nullable=False),
    sa.Column('city', sa.String(), nullable=True),
    sa.Column('organ', sa.String(), nullable=True),
    sa.Column('unity', sa.String(), nullable=True),
    sa.Column('institution', sa.String(), nullable=True),
    sa.Column('public_place', sa.String(), nullable=True),
    sa.Column('district', sa.String(), nullable=True),
    sa.Column('cep', sa.String(), nullable=True),
    sa.Column('mailbox', sa.String(), nullable=True),
    sa.Column('fax', sa.String(), nullable=True),
    sa.Column('url_homepage', sa.String(), nullable=True),
    sa.Column('telephone', sa.String(), nullable=True),
    sa.Column('country', sa.String(), nullable=True),
    sa.Column('uf', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['researcher_id'], ['researcher.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('researcher_area_expertise',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('researcher_id', sa.UUID(), nullable=False),
    sa.Column('sub_area_expertise_id', sa.UUID(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=True),
    sa.Column('area_expertise_id', sa.UUID(), nullable=True),
    sa.Column('great_area_expertise_id', sa.UUID(), nullable=True),
    sa.Column('area_specialty_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['area_expertise_id'], ['area_expertise.id'], ),
    sa.ForeignKeyConstraint(['area_specialty_id'], ['area_specialty.id'], ),
    sa.ForeignKeyConstraint(['great_area_expertise_id'], ['great_area_expertise.id'], ),
    sa.ForeignKeyConstraint(['researcher_id'], ['researcher.id'], ),
    sa.ForeignKeyConstraint(['sub_area_expertise_id'], ['sub_area_expertise.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('researcher_ind_prod',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('researcher_id', sa.UUID(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('ind_prod_article', sa.Float(), nullable=True),
    sa.Column('ind_prod_book', sa.Float(), nullable=True),
    sa.Column('ind_prod_book_chapter', sa.Float(), nullable=True),
    sa.Column('ind_prod_software', sa.Float(), nullable=True),
    sa.Column('ind_prod_report', sa.Float(), nullable=True),
    sa.Column('ind_prod_granted_patent', sa.Float(), nullable=True),
    sa.Column('ind_prod_not_granted_patent', sa.Float(), nullable=True),
    sa.Column('ind_prod_guidance', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['researcher_id'], ['researcher.id'], ),
    sa.PrimaryKeyConstraint('researcher_id', 'year')
    )
    op.create_table('researcher_production',
    sa.Column('researcher_id', sa.UUID(), nullable=False),
    sa.Column('city', sa.String(), nullable=True),
    sa.Column('great_area', sa.String(), nullable=True),
    sa.Column('great_area_', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('articles', sa.Integer(), nullable=True),
    sa.Column('book_chapters', sa.Integer(), nullable=True),
    sa.Column('book', sa.Integer(), nullable=True),
    sa.Column('patent', sa.Integer(), nullable=True),
    sa.Column('software', sa.Integer(), nullable=True),
    sa.Column('brand', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['researcher_id'], ['researcher.id'], ),
    sa.PrimaryKeyConstraint('researcher_id')
    )
    op.create_table('researcher_professional_experience',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('researcher_id', sa.UUID(), nullable=False),
    sa.Column('enterprise', sa.String(), nullable=False),
    sa.Column('start_year', sa.Integer(), nullable=False),
    sa.Column('end_year', sa.Integer(), nullable=True),
    sa.Column('employment_type', sa.String(), nullable=True),
    sa.Column('other_employment_type', sa.String(), nullable=True),
    sa.Column('functional_classification', sa.String(), nullable=True),
    sa.Column('other_functional_classification', sa.String(), nullable=True),
    sa.Column('workload_hours_weekly', sa.Integer(), nullable=True),
    sa.Column('exclusive_dedication', sa.Boolean(), nullable=True),
    sa.Column('additional_info', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['researcher_id'], ['researcher.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('short_course',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('researcher_id', sa.UUID(), nullable=True),
    sa.Column('production_sequence', sa.Integer(), nullable=True),
    sa.Column('title_en', sa.String(), nullable=True),
    sa.Column('year', sa.String(), nullable=True),
    sa.Column('country', sa.String(), nullable=True),
    sa.Column('language', sa.String(), nullable=True),
    sa.Column('dissemination_medium', sa.String(), nullable=True),
    sa.Column('homepage', sa.String(), nullable=True),
    sa.Column('doi', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['researcher_id'], ['researcher.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('short_course_taught',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('researcher_id', sa.UUID(), nullable=True),
    sa.Column('production_sequence', sa.Integer(), nullable=True),
    sa.Column('title_en', sa.String(), nullable=True),
    sa.Column('year', sa.String(), nullable=True),
    sa.Column('country', sa.String(), nullable=True),
    sa.Column('language', sa.String(), nullable=True),
    sa.Column('dissemination_medium', sa.String(), nullable=True),
    sa.Column('homepage', sa.String(), nullable=True),
    sa.Column('doi', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['researcher_id'], ['researcher.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('social_media_website_blog',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('researcher_id', sa.UUID(), nullable=True),
    sa.Column('production_sequence', sa.Integer(), nullable=True),
    sa.Column('title_en', sa.String(), nullable=True),
    sa.Column('year', sa.String(), nullable=True),
    sa.Column('country', sa.String(), nullable=True),
    sa.Column('language', sa.String(), nullable=True),
    sa.Column('dissemination_medium', sa.String(), nullable=True),
    sa.Column('homepage', sa.String(), nullable=True),
    sa.Column('doi', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['researcher_id'], ['researcher.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('software',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('platform', sa.String(), nullable=True),
    sa.Column('goal', sa.String(), nullable=True),
    sa.Column('relevance', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('has_image', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('environment', sa.String(), nullable=True),
    sa.Column('availability', sa.String(), nullable=True),
    sa.Column('financing_institutionc', sa.String(), nullable=True),
    sa.Column('researcher_id', sa.UUID(), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('is_new', sa.Boolean(), server_default=sa.text('true'), nullable=True),
    sa.Column('stars', sa.Integer(), server_default=sa.text('0'), nullable=True),
    sa.Column('code', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['researcher_id'], ['researcher.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('technical_work',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('researcher_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('country', sa.String(), nullable=True),
    sa.Column('nature', sa.String(), nullable=True),
    sa.Column('funding_institution', sa.String(), nullable=True),
    sa.Column('duration', sa.Integer(), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['researcher_id'], ['researcher.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('technical_work_presentation',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('researcher_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('country', sa.String(), nullable=True),
    sa.Column('nature', sa.String(), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('event_name', sa.String(), nullable=True),
    sa.Column('promoting_institution', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['researcher_id'], ['researcher.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('technical_work_program',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('researcher_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('country', sa.String(), nullable=True),
    sa.Column('nature', sa.String(), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('theme', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['researcher_id'], ['researcher.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('technological_product',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('researcher_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('country', sa.String(), nullable=True),
    sa.Column('nature', sa.String(), nullable=True),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['researcher_id'], ['researcher.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bibliographic_production_article',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('bibliographic_production_id', sa.UUID(), nullable=False),
    sa.Column('periodical_magazine_id', sa.UUID(), nullable=False),
    sa.Column('volume', sa.String(), nullable=True),
    sa.Column('fascicle', sa.String(), nullable=True),
    sa.Column('series', sa.String(), nullable=True),
    sa.Column('start_page', sa.String(), nullable=True),
    sa.Column('end_page', sa.String(), nullable=True),
    sa.Column('place_publication', sa.String(), nullable=True),
    sa.Column('periodical_magazine_name', sa.String(), nullable=True),
    sa.Column('issn', sa.String(), nullable=True),
    sa.Column('qualis', sa.String(), nullable=True),
    sa.Column('jcr', sa.String(), nullable=True),
    sa.Column('jcr_link', sa.String(), nullable=True),
    sa.Column('stars', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['bibliographic_production_id'], ['bibliographic_production.id'], ),
    sa.ForeignKeyConstraint(['periodical_magazine_id'], ['periodical_magazine.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bibliographic_production_book',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('bibliographic_production_id', sa.UUID(), nullable=False),
    sa.Column('isbn', sa.String(), nullable=True),
    sa.Column('qtt_volume', sa.String(), nullable=True),
    sa.Column('qtt_pages', sa.String(), nullable=True),
    sa.Column('num_edition_revision', sa.String(), nullable=True),
    sa.Column('num_series', sa.String(), nullable=True),
    sa.Column('publishing_company', sa.String(), nullable=True),
    sa.Column('publishing_company_city', sa.String(), nullable=True),
    sa.Column('stars', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['bibliographic_production_id'], ['bibliographic_production.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bibliographic_production_book_chapter',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('bibliographic_production_id', sa.UUID(), nullable=False),
    sa.Column('book_title', sa.String(), nullable=True),
    sa.Column('isbn', sa.String(), nullable=True),
    sa.Column('start_page', sa.String(), nullable=True),
    sa.Column('end_page', sa.String(), nullable=True),
    sa.Column('qtt_volume', sa.String(), nullable=True),
    sa.Column('organizers', sa.String(), nullable=True),
    sa.Column('num_edition_revision', sa.String(), nullable=True),
    sa.Column('num_series', sa.String(), nullable=True),
    sa.Column('publishing_company', sa.String(), nullable=True),
    sa.Column('publishing_company_city', sa.String(), nullable=True),
    sa.Column('stars', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['bibliographic_production_id'], ['bibliographic_production.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bibliographic_production_work_in_event',
    sa.Column('bibliographic_production_id', sa.UUID(), nullable=False),
    sa.Column('event_classification', sa.String(), nullable=True),
    sa.Column('event_name', sa.String(), nullable=True),
    sa.Column('event_city', sa.String(), nullable=True),
    sa.Column('event_year', sa.Integer(), nullable=True),
    sa.Column('proceedings_title', sa.String(), nullable=True),
    sa.Column('volume', sa.String(), nullable=True),
    sa.Column('issue', sa.String(), nullable=True),
    sa.Column('series', sa.String(), nullable=True),
    sa.Column('start_page', sa.String(), nullable=True),
    sa.Column('end_page', sa.String(), nullable=True),
    sa.Column('publisher_name', sa.String(), nullable=True),
    sa.Column('publisher_city', sa.String(), nullable=True),
    sa.Column('event_name_english', sa.String(), nullable=True),
    sa.Column('identifier_number', sa.String(), nullable=True),
    sa.Column('isbn', sa.String(), nullable=True),
    sa.Column('stars', sa.Integer(), server_default=sa.text('0'), nullable=True),
    sa.ForeignKeyConstraint(['bibliographic_production_id'], ['bibliographic_production.id'], ),
    sa.PrimaryKeyConstraint('bibliographic_production_id')
    )
    op.create_table('openalex_article',
    sa.Column('article_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('article_institution', sa.String(), nullable=True),
    sa.Column('issn', sa.String(), nullable=True),
    sa.Column('authors_institution', sa.String(), nullable=True),
    sa.Column('abstract', sa.Text(), nullable=True),
    sa.Column('authors', sa.String(), nullable=True),
    sa.Column('language', sa.String(), nullable=True),
    sa.Column('citations_count', sa.Integer(), nullable=True),
    sa.Column('pdf', sa.String(), nullable=True),
    sa.Column('landing_page_url', sa.String(), nullable=True),
    sa.Column('keywords', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['article_id'], ['bibliographic_production.id'], ),
    sa.PrimaryKeyConstraint('article_id')
    )
    op.create_table('process_author',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('process_id', sa.UUID(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=False),
    sa.Column('citation_name', sa.String(), nullable=True),
    sa.Column('author_order', sa.Integer(), nullable=True),
    sa.Column('cnpq_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['process_id'], ['process_or_technique.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('process_keyword',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('process_id', sa.UUID(), nullable=False),
    sa.Column('keyword', sa.Text(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['process_id'], ['process_or_technique.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('process_knowledge_area',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('process_id', sa.UUID(), nullable=False),
    sa.Column('major_area', sa.String(), nullable=True),
    sa.Column('area_name', sa.String(), nullable=True),
    sa.Column('sub_area_name', sa.String(), nullable=True),
    sa.Column('specialty_name', sa.String(), nullable=True),
    sa.Column('order', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['process_id'], ['process_or_technique.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('research_project_components',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('lattes_id', sa.String(), nullable=True),
    sa.Column('citations', sa.String(), nullable=True),
    sa.Column('coordinator', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['research_project.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('research_project_foment',
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('agency_name', sa.String(), nullable=True),
    sa.Column('agency_code', sa.String(), nullable=True),
    sa.Column('nature', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['research_project.id'], ),
    sa.PrimaryKeyConstraint('project_id')
    )
    op.create_table('research_project_production',
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('type', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['research_project.id'], ),
    sa.PrimaryKeyConstraint('project_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    op.execute('DROP SCHEMA IF EXISTS admin_ufmg CASCADE')
    op.execute('DROP SCHEMA IF EXISTS admin CASCADE')
    op.execute('DROP SCHEMA IF EXISTS ufmg CASCADE')
    op.execute('DROP SCHEMA IF EXISTS logs CASCADE')
    op.execute('DROP EXTENSION IF EXISTS unaccent')
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('research_project_production')
    op.drop_table('research_project_foment')
    op.drop_table('research_project_components')
    op.drop_table('process_knowledge_area')
    op.drop_table('process_keyword')
    op.drop_table('process_author')
    op.drop_table('openalex_article')
    op.drop_table('bibliographic_production_work_in_event')
    op.drop_table('bibliographic_production_book_chapter')
    op.drop_table('bibliographic_production_book')
    op.drop_table('bibliographic_production_article')
    op.drop_table('technological_product')
    op.drop_table('technical_work_program')
    op.drop_table('technical_work_presentation')
    op.drop_table('technical_work')
    op.drop_table('software')
    op.drop_table('social_media_website_blog')
    op.drop_table('short_course_taught')
    op.drop_table('short_course')
    op.drop_table('researcher_professional_experience')
    op.drop_table('researcher_production')
    op.drop_table('researcher_ind_prod')
    op.drop_table('researcher_area_expertise')
    op.drop_table('researcher_address')
    op.drop_table('research_report')
    op.drop_table('research_project')
    op.drop_table('research_group_researcher')
    op.drop_table('relevant_production')
    op.drop_table('registered_cultivar')
    op.drop_table('radio_or_tv_program')
    op.drop_table('publishing')
    op.drop_table('process_or_technique')
    op.drop_table('patent')
    op.drop_table('participation_events')
    op.drop_table('other_technical_production')
    op.drop_table('openalex_researcher')
    op.drop_table('mockup')
    op.drop_table('maintenance_artistic_work')
    op.drop_table('letter_map_or_similar')
    op.drop_table('labs')
    op.drop_table('industrial_design')
    op.drop_table('guidance')
    op.drop_table('graduate_program_student')
    op.drop_table('graduate_program_researcher')
    op.drop_table('foment')
    op.drop_table('event_organization')
    op.drop_table('education')
    op.drop_table('didactic_material')
    op.drop_table('brand')
    op.drop_table('bibliographic_production')
    op.drop_table('artistic_production')
    op.drop_table('advisory_activity')
    op.drop_table('researcher')
    op.drop_table('area_specialty')
    op.drop_table('sub_area_expertise')
    op.drop_table('research_lines_programs')
    op.drop_table('city')
    op.drop_table('users_roles', schema='admin')
    op.drop_table('graduate_program_student', schema='admin')
    op.drop_table('graduate_program_researcher', schema='admin')
    op.drop_table('departament_technician', schema='ufmg')
    op.drop_table('state')
    op.drop_table('sdg_alignment')
    op.drop_table('research_lines')
    op.drop_table('graduate_program')
    op.drop_table('area_expertise')
    op.drop_table('researcher', schema='admin_ufmg')
    op.drop_table('disciplines', schema='admin_ufmg')
    op.drop_table('department_technician', schema='admin_ufmg')
    op.drop_table('department_researcher', schema='admin_ufmg')
    op.drop_table('weights', schema='admin')
    op.drop_table('users', schema='admin')
    op.drop_table('researcher_institution', schema='admin')
    op.drop_table('permission', schema='admin')
    op.drop_table('graduate_program', schema='admin')
    op.drop_table('technician', schema='ufmg')
    op.drop_table('researcher_data', schema='ufmg')
    op.drop_table('researcher', schema='ufmg')
    op.drop_table('mandate', schema='ufmg')
    op.drop_table('departament_researcher', schema='ufmg')
    op.drop_table('departament', schema='ufmg')
    op.drop_table('seeder_versions')
    op.drop_table('sdg')
    op.drop_table('research_group')
    op.drop_table('research_dictionary')
    op.drop_table('periodical_magazine')
    op.drop_table('routine', schema='logs')
    op.drop_table('jcr')
    op.drop_table('institution')
    op.drop_table('great_area_expertise')
    op.drop_table('graduate_program_ind_prod')
    op.drop_table('country')
    op.drop_table('technician', schema='admin_ufmg')
    op.drop_table('department', schema='admin_ufmg')
    op.drop_table('roles', schema='admin')
    op.drop_table('researcher', schema='admin')
    op.drop_table('newsletter_subscribers', schema='admin')
    op.drop_table('institution', schema='admin')
    op.drop_table('feedback', schema='admin')
    # ### end Alembic commands ###
