services:
  conectee_db:
    extends:
      file: base.compose.yaml
      service: base_db
    volumes:
      - conectee_db:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: conectee

  conectee_hop:
    extends:
      file: ../base.compose.yaml
      service: base_hop

  conectee_api:
    extends:
      file: base.compose.yaml
      service: base_api
    ...

volumes:
  conectee_db:
  conectee_xml: