name: ${COMPOSE_PROJECT_NAME}

services:
  conectee_db:
    extends:
      file: base.compose.yaml
      service: base_db
    volumes:
      - conectee_db:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: conectee

  conectee_hop:
    extends:
      file: base.compose.yaml
      service: base_hop
    container_name: conectee_hop
    ports:
      - "8080:8080"
    volumes:
      - conectee_xml:/files/jade-extrator/datasets/lattes_xml
    depends_on:
      conectee_db:
        condition: service_healthy

  conectee_api:
    extends:
      file: base.compose.yaml
      service: base_api
    environment:
      ALTERNATIVE_CNPQ_SERVICE: True
      DATABASE_URL: postgresql+asyncpg://postgres:postgres@conectee_db:5432/conectee
      ADMIN_DATABASE_URL: postgresql+asyncpg://postgres:postgres@conectee_db:5432/conectee_admin
    depends_on:
      conectee_db:
        condition: service_healthy
    volumes:
      - conectee_xml:/app/storage/xml

volumes:
  conectee_db:
  conectee_xml: