services:
  conectee_db:
    extends:
      file: base.compose.yaml
      service: base_db
    container_name: prod_conectee_db
    volumes:
      - conectee_db:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: conectee

  conectee_hop:
    extends:
      file: base.compose.yaml
      service: base_hop
    container_name: prod_conectee_hop
    environment:
      HOP_PROJECT_NAME: Jade-Extrator
      HOP_PROJECT_FOLDER: /files/jade-extrator
      HOP_RUN_PARAMETERS: "DATABASE_URL=jdbc:postgresql://conectee_db:5432/conectee?user=postgres&password=postgres,ADMIN_DATABASE_URL=jdbc:postgresql://conectee_db:5432/conectee_admin?user=postgres&password=postgres"
    volumes:
      - ./storage/xml:/files/jade-extrator/datasets/lattes_xml
    depends_on:
      conectee_db:
        condition: service_healthy

  conectee_api:
    extends:
      file: base.compose.yaml
      service: base_api
    container_name: prod_conectee_api
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql+asyncpg://postgres:postgres@conectee_db:5432/conectee
      ADMIN_DATABASE_URL: postgresql+asyncpg://postgres:postgres@conectee_db:5432/conectee_admin
    depends_on:
      conectee_db:
        condition: service_healthy

volumes:
  conectee_db: