name: ${COMPOSE_PROJECT_NAME}

services:
  db:
    extends:
      file: base.compose.yaml
      service: base_db
    environment:
      POSTGRES_DB: ${COMPOSE_PROJECT_NAME}
    volumes:
      - db:/var/lib/postgresql/data

  hop:
    extends:
      file: base.compose.yaml
      service: base_hop
    volumes:
      - xml:/files/jade-extrator/datasets/lattes_xml
    depends_on:
      db:
        condition: service_healthy

  api:
    extends:
      file: base.compose.yaml
      service: base_api
    image: gleidsoncosta/simcc-back:latest
    ports:
      - "${API_PORT}:8000"
    environment:
      DATABASE_URL: "postgresql+asyncpg://postgres:postgres@db:5432/${COMPOSE_PROJECT_NAME}"
      ADMIN_DATABASE_URL: "postgresql+asyncpg://postgres:postgres@admin_db:5432/${COMPOSE_PROJECT_NAME}_admin"
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - xml:/app/storage/xml

volumes:
  db:
  xml: