services:
  db:
    extends:
      file: base.compose.yaml
      service: base_db
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: db

  hop:
    extends:
      file: base.compose.yaml
      service: base_hop
    ports:
      - "8080:8080"
    environment:
      HOP_RUN_PARAMETERS: DATABASE_URL=jdbc:postgresql://db:5432/db?user=postgres&password=postgres,ADMIN_DATABASE_URL=jdbc:postgresql://db:5435/db_admin?user=postgres&password=postgres
    volumes:
      - xml:/files/jade-extrator/datasets/lattes_xml
    depends_on:
      db:
        condition: service_healthy

  api:
    extends:
      file: base.compose.yaml
      service: base_api
    image: gleidsoncosta/simcc-back:latest
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql+asyncpg://postgres:postgres@db:5432/db
      ADMIN_DATABASE_URL: postgresql+asyncpg://postgres:postgres@db:5432/db_admin
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - xml:/app/storage/xml

volumes:
  db:
  xml: