name: ${COMPOSE_PROJECT_NAME}

services:
  simcc_db:
    extends:
      file: base.compose.yaml
      service: base_db
    volumes:
      - simcc_db:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: simcc

  simcc_hop:
    extends:
      file: base.compose.yaml
      service: base_hop
    container_name: simcc_hop
    volumes:
      - simcc_xml:/files/jade-extrator/datasets/lattes_xml
    depends_on:
      simcc_db:
        condition: service_healthy

  simcc_api:
    extends:
      file: base.compose.yaml
      service: base_api
    environment:
      DATABASE_URL: postgresql+asyncpg://postgres:postgres@simcc_db:5432/simcc
    depends_on:
      simcc_db:
        condition: service_healthy
    volumes:
      - simcc_xml:/app/storage/xml

volumes:
  simcc_db:
  simcc_xml: